### ISSUE TITLE
Proxy in 0.14.5 is broken

### ISSUE THREAD

**Issue by Deathspike** [phonegap/connect-phonegap#104]
The proxy middleware has broken down going from 0.14.4 to 0.14.5. It seems like the `host` header is not set correctly. You can test this on any site that serves sites depending on the `host` header (e.g. almost every site on a shared host).

Probably because `delete req.headers.host;` was dropped as well in that patch?

**Comment by Deathspike** [comment]
To confirm, yes putting `delete req.headers.host;` above `req.url = url;` (https://github.com/phonegap/connect-phonegap/blob/master/lib/middleware/proxy.js#L34) fixes the problem.

A pull request seems a little overkill for this one-line patch :-)

**Comment by mwbrooks** [comment]
Hi @Deathspike,

Thanks for catching this issue so quickly! I've published a patch to help you out. However, could you provide me with a real-world example that I can use to test the issue? Currently, we don't have a test case to catch this scenario and I'm unsure how to structure it.

Published `connect-phonegap@0.14.6`
Published `phonegap@4.1.2-0.22.12`

Thanks!
Michael

**Comment by Deathspike** [comment]
Sure!

There are many sites that require a valid host header to route into the correct application, and won't work while approached with an incorrect host header or by IP. IIS, Apache and nginx tend to route this way by default. For example, the ASP.NET site runs on http://www.asp.net/ and the equivalent IP at the moment is 168.62.43.5. Go to http://168.62.43.5/ and it won't show the site. Request with an incorrect header, or missing header, and you get a different site too. Here is the same thing as a proxy script:

	var http = require('http'),
		httpProxy = require('http-proxy'),
		proxy = httpProxy.createProxyServer({});

	http.createServer(function(req, res) {
		// delete req.headers.host;
		proxy.web(req, res, { target: 'http://www.asp.net/' });
	}).listen(3000);

Note that when the `delete` is uncommented, you won't see the site. Otherwise you will. I can create a full test with a local server that requires a correct host header if you desire, please let me know :)

**Comment by filmaj** [comment]
This is resolved. I am closing it.
