### ISSUE TITLE
phonegap serve has a tendency to return unknown as the ip address

### ISSUE THREAD

**Issue by timkim** [phonegap/connect-phonegap#107]
On osx, hit `phonegap serve`. Most of the time it will return the ip address of the machine. Other times, it returns `unknown`. 

```
$ phonegap serve
[phonegap] starting app server...
[phonegap] listening on unknown:3000
[phonegap] 
[phonegap] ctrl-c to stop the server
```

**Comment by mwbrooks** [comment]
Published as `connect-phonegap@0.14.8`

Available in `phonegap@4.2.0-0.24.2`
