### ISSUE TITLE
TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by Deathspike** [phonegap/connect-phonegap#117]
I am using `connect-phonegap` like this at the moment (don't mind the bad require):

    var app = require('connect')();
    var phonegap = require('phonegap/node_modules/connect-phonegap');
    var serveStatic = require('serve-static')
    app.use(serveStatic('src'));
    app.use(phonegap({autoreload: false}))
    app.listen(3000);

Which results in the following error when fetching `http://localhost:3000/cordova.js`:

    TypeError: Arguments to path.join must be strings
       at f (path.js:200:13)
       at Object.filter (native)
       at Object.win32.join (path.js:205:38)
       at Object.handle (C:\Users\roel\Desktop\apps-v5\node_modules\phonegap\node_modules\connect-phonegap\lib\middleware\cordova\cordova.js:22:33)
       at next (C:\Users\roel\Desktop\apps-v5\node_modules\phonegap\node_modules\connect-phonegap\node_modules\connect\lib\proto.js:193:15)
       at resume (C:\Users\roel\Desktop\apps-v5\node_modules\phonegap\node_modules\connect-phonegap\node_modules\connect\lib\middleware\static.js:65:7)
       at SendStream.error (C:\Users\roel\Desktop\apps-v5\node_modules\phonegap\node_modules\connect-phonegap\node_modules\connect\lib\middleware\static.js:80:37)
       at SendStream.emit (events.js:107:17)
       at SendStream.error (C:\Users\roel\Desktop\apps-v5\node_modules\phonegap\node_modules\connect-phonegap\node_modules\connect\node_modules\send\lib\send.js:147:51)
       at SendStream.onStatError (C:\Users\roel\Desktop\apps-v5\node_modules\phonegap\node_modules\connect-phonegap\node_modules\connect\node_modules\send\lib\send.js:248:48) 

Here `req.session.device.platform` is `platform` and `req.session.device.version` is undefined.

I have not yet found a solution yet, or why this happened. Some context: the goal I have with doing things this way, rather than using a `phonegap serve` is to allow TypeScript sources to be served from a different directory. This way I can easily make a differentiation between assets and code, and deploy only a minified bundle after building.

**Comment by mwbrooks** [comment]
Hi @Deathspike,

Here is a snippet from one of my setup that will serve a PG app from a web url:

```
/*!
 * Module dependencies.
 */

var connect = require('connect'),
    phonegap = require('connect-phonegap'),
    app = connect();

/*!
 * Create Express app and server.
 */

app.use(phonegap());

var port = process.env.PORT || 3000;
app.listen(port);
```

All in all, it looks similar to your approach.

My only suggestion is that `process.cwd()` must be a PhoneGap app. Specifically, it expects `www/` to be available:

```
path.join(process.cwd(), 'www');
```

Glancing at your sample code, it looks as though 'src' may be your asset directory instead of 'www'.

**Comment by Deathspike** [comment]
The current work directory is actually in the root so I have

    * src
    * www
    * node_modules
    * bower_components

I would expect this to work indeed. Your example is almost the same. :/

**Comment by mwbrooks** [comment]
Okay, in that case your file structure looks okay.

It's odd that `req.session.device.platform` is `platform`. If possible, can you try to access `localhost:3000/cordova.js` from Chrome. If it fails, try from a mobile device's browser. My thought is that the `user-agent` is may be detected incorrectly. Truthfully, `connect-phonegap` is not intended to support desktop browsers even though it kinda does naturally. However, depending on what browser you use, I can see it failing to detect the proper user-agent platform.

**Comment by Deathspike** [comment]
I have no explanation.

When I got into work today, I started the previously posted script again and hit the `cordova.js` file with Chrome... and I got the Android script. No error whatsoever. Hitting it with Internet Explorer gives the same problem as before; I suppose it doesn't detect IE as IEMobile. The truly odd part is that I was testing with Chrome yesterday, and without changes, it works today. How very odd.

Perhaps something weird with the session happened? Anyway, thanks a lot! Feel free to close (leaving it open for that last Q)

**Comment by mwbrooks** [comment]
@Deathspike Strange. Any chance that you were debugging in Chrome and using Web Inspector to spoof the user-agent as another browser? That's my only guess. Regardless, I'm happy to hear that we've figured it out. In the near future, we'll be adding desktop browser support :)
