### ISSUE TITLE
Proxy with /appzip

### ISSUE THREAD

**Issue by Deathspike** [phonegap/connect-phonegap#118]
Proxying on an application served as appzip does not work.
- `/proxy/` means nothing in a local setting
- remote requests w/o proxy don't work either

**Comment by Deathspike** [comment]
Because it's `file:///data/data/com.adobe.....` all the restrictions of file:// apply.

**Comment by filmaj** [comment]
With the developer app using content-sync plugin, proxying is no longer needed for that case. Closing this down. If you feel like this is still a legitimate issue, feel free to re-open.
