### ISSUE TITLE
Injected scripts should listen to DOM load

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/connect-phonegap#120]
As pointed out by #119, we currently listen for `deviceready`. This has the downside of not initializing when the developer does not include `cordova.js`.

**Comment by surajpindoria** [comment]
This issue is related to #161.

**Comment by surajpindoria** [comment]
After investigating this it looks like there is no way around using `deviceready` in the injected scripts. Changing the event works fine if `cordova.js` is included, but there are issues if we have problems loading it. During the update process on the device we make calls to cordova plugins, no `cordova.js` means no access to plugins, therefore we cannot update.
