### ISSUE TITLE
WP8 gets multiple session ids 

### ISSUE THREAD

**Issue by timkim** [phonegap/connect-phonegap#125]
For the `Quick Content Sync Updates`, it appears that wp8 likes to get two (or perhaps more) session IDs. This is really annoying as I am using the sessionIDs to determine which devices need which files have been updated.

**Comment by mwbrooks** [comment]
@timkim Is this still an issue?

**Comment by timkim** [comment]
@mwbrooks Oh whoops - totally missed this one. Closing it out.
