### ISSUE TITLE
Does not fully work with symlinked files

### ISSUE THREAD

**Issue by Globegitter** [phonegap/connect-phonegap#128]
This line https://github.com/phonegap/connect-phonegap/blob/master/lib/middleware/zip.js#L80 breaks the `phonegap serve` command when symlinks are being used because the walk library returns the original file path and has no option to also return the original file path.

**Comment by eliotsykes** [comment]
@Globegitter also see #116

**Comment by Globegitter** [comment]
Ahh thanks @eliotsykes missed that completely.

**Comment by mwbrooks** [comment]
I believe we now properly support sym-links. Let me know if there are still issues and I'll reopen this one.
