### ISSUE TITLE
Implement contacts plugin

### ISSUE THREAD

**Issue by surajpindoria** [phonegap/connect-phonegap#133]

**Comment by mwbrooks** [comment]
PR sent: https://github.com/apache/cordova-plugin-contacts/pull/73

**Comment by mwbrooks** [comment]
@surajpindoria what's the status of this sucker?

**Comment by filmaj** [comment]
@surajpindoria can you clarify what this issue is about and what needs to be done for this?

**Comment by surajpindoria** [comment]
This was from when we first released browser, we were discussing how to implement all the plugins to either provide some support (real or fake) or just error out gracefully. On first pass I made a hacky implementation that used localStorage to imitate the features of the contacts plugin. Second time we just did error support which has been merged. This can be closed.
