### ISSUE TITLE
Content Security Policy can block Live Reload

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/connect-phonegap#143]
See: https://github.com/phonegap/phonegap-app-developer/issues/309#issuecomment-170306084

We should find a proper solution for this, otherwise display a message to help the user when access is blocked.

**Comment by arrayown** [comment]
As per [this StackOverflow comment](http://stackoverflow.com/questions/32986074/content-security-policy-meta-tag-for-allowing-web-socket), replacing the default Cordova meta tag with the one below fixes the problem for me. Tested with version 1.4 and latest 1.5.13:
```
<meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src * 'unsafe-inline' 'unsafe-eval'">
```

Hope this helps anyone.

**Comment by mwbrooks** [comment]
@arrayown thanks a bunch for that CSP meta tag. I've added it to the above commit, which helps resolve CSP issues.

**Comment by mwbrooks** [comment]
Published and available in:
```
connect-phonegap@0.20.1`
phonegap@5.5.2
```

**Comment by mattzuba** [comment]
This forced CSP tag is causing me issues, overriding my custom CSP tag when trying to test with the Phonegap Mobile app.  This shouldn't completely wipe out an already created CSP tag, but rather *add* anything that might be missing to it, or this commit should just be backed out and the dev should be responsible for having the proper CSP tag in place.  With this in place, if the dev forgets it, the phonegap dev app could make their app appear to work okay, but upon building and test as an actual app on the phone, it would fail, causing head scratching.
