### ISSUE TITLE
Tests are not completing on Windows

### ISSUE THREAD

**Issue by surajpindoria** [phonegap/connect-phonegap#158]
Running the tests on Windows, `npm test`, exits before all the tests have been run with no error messages.

**Comment by surajpindoria** [comment]
Narrowed down the cause of this. The tests are getting messed up in [zip.spec.js](https://github.com/phonegap/connect-phonegap/blob/master/spec/middleware/zip.spec.js#L64) when we are testing with symlinks. Windows doesn't really do symlinks well, not sure how to handle this.

@mwbrooks Any suggestions? I was thinking just skip this test on Windows.

**Comment by mwbrooks** [comment]
It's dangerous to skip the test, because what if the sym-link code causes a crash on Windows? I agree it may not make sense to actually test sym-links on Windows (not sure if we want to support shortcuts), but we should ensure that the code is stable.

**Comment by filmaj** [comment]
As part of the upgrade for jasmine2, [I skipped the test](https://github.com/phonegap/connect-phonegap/commit/fa842cb97189480ea118ce6ea9d67c9559643e12). I think with respect to ensuring nothing crashes on Windows, appveyor CI runs give us that confidence. If anything, keeping behaviour as is (tests stopping silently and jasmine crashing) gives us less coverage on Windows.

Closing this.
