### ISSUE TITLE
Out-dated walkdir module causing issues on Windows

### ISSUE THREAD

**Issue by mattzuba** [phonegap/connect-phonegap#164]
Walkdir had a bug prior to it's 0.0.10 version that didn't properly detect when multiple files on Windows contained the same inode, which would cause it not to walk those files.  I'm suffering from this bug during the `/__api__/appzip` call.  The zip file that is going to my phone is missing files because walkdir is skipping them during the zip process.

ref: https://github.com/soldair/node-walkdir/pull/22

**Comment by surajpindoria** [comment]
I have updated the version of `walkdir` to handle this. Thanks for pointing out this issue to us @mattzuba!

https://github.com/phonegap/connect-phonegap/commit/0e7433ab60ebf1ced61a5df0b9b4680cb136bc7b
