### ISSUE TITLE
console.log, console.warn, etc ignore multiple parameters

### ISSUE THREAD

**Issue by bladeSk** [phonegap/connect-phonegap#167]
The original versions of `console.*` can print multiple parameters, Phonegap breaks this and makes `console.*` functions always output just the first parameter.

Here's a PR with a working fix: https://github.com/phonegap/connect-phonegap/pull/166

**Comment by jfurfaro** [comment]
On a related note, Phonegap also omits some other useful console functions, especially when working in the browser. (`console.time`, `console.timeEnd`, etc.). It would be better to only overwrite the individual methods on `window.console` rather than point it to a new object altogether.

**Comment by jfurfaro** [comment]
I created a pull request [#168](https://github.com/phonegap/connect-phonegap/pull/168) with some changes that worked for me

**Comment by surajpindoria** [comment]
I have merged in both PR's. Closing this issue, thanks for your contributions @bladeSk & @jfurfaro!

**Comment by mwbrooks** [comment]
Awesome! Thanks @surajpindoria, @bladeSk, and @jfurfaro!
