### ISSUE TITLE
Using connect as a standalone module no longer works

### ISSUE THREAD

**Issue by surajpindoria** [phonegap/connect-phonegap#171]
With the new method for injecting scripts we need to provide acceptable defaults for all options, otherwise scripts will not be injected

**Comment by filmaj** [comment]
Hmm, I've been playing with this module on its own (w/ `connect`) and it seems to work fine.

What isn't working @surajpindoria ?

**Comment by surajpindoria** [comment]
Have you been using like this?

https://github.com/phonegap/connect-phonegap#standalone

**Comment by filmaj** [comment]
Both with and without `connect`, yeah. Here's a local one I use for testing:

```
~/src/connect-phonegap on master via ⬢ v6.10.1
➔ cat ../connect.js
var phonegap = require('./connect-phonegap/lib/index.js');
phonegap.listen({
    port:3000,
    browser:true
}).on('error', function(e) {
    // an error occured
    console.error('Uh oh!', e);
}).on('log', function() {
    console.log.apply(this, arguments);
});
```

Works well.

**Comment by surajpindoria** [comment]
Ahh I wasn't using the browser option. That does the trick now, maybe then we should update this issue to better document the various options we allow in connect.

**Comment by filmaj** [comment]
I filed #189 exactly for that :D

**Comment by surajpindoria** [comment]
Cool, I'll close this then.
