### ISSUE TITLE
Move browser functionality

### ISSUE THREAD

**Issue by maverickmishra** [phonegap/connect-phonegap#176]
Move browser functionality from connect-phonegap to phonegap - cli serve.

**Comment by purplecabbage** [comment]
> "This has to do with the decouple work. Browser stuff in connect is the only reason we shell out to cordova. But we are trying to get rid of `phonegap-cordova-dependence`. So just moving the browser logic into the CLI "
> @surajpindoria

**Comment by filmaj** [comment]
I believe this is now complete. Closing. If I'm wrong, @stevengill / @maverickmishra, please re-open.
