### ISSUE TITLE
Remove Desktop App Windows browser platform add workaround

### ISSUE THREAD

**Issue by surajpindoria** [phonegap/connect-phonegap#181]
### PhoneGap CLI, node & npm versions

PG: 6.3.3
Node/npm: all
### Expected Behaviour

When using the desktop app on Windows, use proper method to add browser platform too a project
### Actual Behaviour

Currently using workaround to achieve browser platform add
### Steps to Reproduce

Use desktop app and serve a project without browser platform added

**Comment by stevengill** [comment]
This PR right? https://github.com/phonegap/connect-phonegap/pull/177
