### ISSUE TITLE
Document all options for this module

### ISSUE THREAD

**Issue by filmaj** [phonegap/connect-phonegap#189]
All of these are not doc'ed in the README:

https://github.com/phonegap/connect-phonegap/blob/92118c11f852da37eb17bc92496d981348847e76/lib/util/scripts-to-inject.js#L29-L37

The events in the readme are wrong too. There is a `log` event, but the `data` event doesn't seem to do much.

**Comment by timkim** [comment]
Ok, updated the readme but the `data` event you are talking about looks like a typo in the docs. The "`data` event" is actually an object returned from the `complete` event. I think the formatting just got messed up or something so it looks like an event. 

Source: https://github.com/phonegap/connect-phonegap/blob/master/lib/serve.js#L33

**Comment by filmaj** [comment]
Hold on. What do the 'injection' events mean? What exactly is meant by autoreload? What does localtunnel do? I think we can do a better job of describing what kinda of behaviours those options do, no? As a totally fresh user, I don't know what these options do, or what an injection event is.
