### ISSUE TITLE
can't set window.location and get warning about CSP change

### ISSUE THREAD

**Issue by tisdall** [phonegap/connect-phonegap#200]
I'm completely new to all this so I'm sorry for my ignorance...  I'm trying to just do `window.location = "https://www.google.com/";` after the `deviceready`.  If I try accessing the app through the browser it seems to have no issue.  If I try accessing it through the PhoneGap Developer Android app it seems to refuse to go to that address and I also get a warning about it updating the Content Security Policy:

`[phonegap] [console.warn] Content Security Policy has been modified to be: <meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline' gap: ws: https://ssl.gstatic.com;style-src 'self' 'unsafe-inline' data: blob:;media-src *;img-src * 'self' data: content:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">`

I don't know enough about CSP to determine if this policy is restricting loading the page I want or not...  But I've already set all the whitelist settings in config.xml to be as permissive as possible and I can't figure out why it's not letting me do this.

### PhoneGap CLI, node & npm versions
phonegap 6.5.0
node v4.2.6
npm 3.5.2

#### Sample Code that illustrates the problem

I commented out the 'js/index.js' component to the default hello-world app and changed it as follows:

```
    <!--<script type="text/javascript" src="js/index.js"></script>-->
    <!--<script type="text/javascript">-->
        <!--app.initialize();-->
    <!--</script>-->
    <script>
        function onDeviceReady() {
            if (navigator.connection.type == Connection.NONE) {
                navigator.notification.alert('An internet connection is required to continue');
            } else {
                window.location = "https://www.google.com/";
            }
        }
        document.addEventListener("deviceready", onDeviceReady, false);
    </script>
```

**Comment by timkim** [comment]
Hi @tisdall 

See this article about setting the the proper whitelisting of urls the app is allowed to navigate to: https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/#navigation-whitelist

Also, since you are trying to do this within the PhoneGap Developer App, you won't be able to navigate to that url because the PhoneGap Developer App is using its own config.xml to read the settings from. So even if you set the config.xml within your own project, the PhoneGap Developer App won't honour that. 

In order to use the PhoneGap Developer App and navigate to the urls you want, you can clone the repo and build the app yourself. See these instructions to do so: http://docs.phonegap.com/references/developer-app/custom-build/ios/

**Comment by tisdall** [comment]
Thank you @timkim .  It seems really odd to me that the PhoneGap Developer App has any sort of restrictions on it (whitelist, CSP, etc).  It's a developer-only application and restrictions would only serve to confuse other developers when things mysteriously don't work.  Any idea why it's set that way?

**Comment by tisdall** [comment]
@timkin ...  I just looked at the app repo, it doesn't look like it has any restrictions.  Are those restrictions just added to the app in the Play store?

**Comment by tisdall** [comment]
@timkim - sorry, I misread it..  it has no whitelist rules so it's disallowing it.  I still don't understand why it would restrict anything like that in a dev-only tool.

**Comment by timkim** [comment]
Hi again @tisdall,

> It seems really odd to me that the PhoneGap Developer App has any sort of restrictions on it (whitelist, CSP, etc). It's a developer-only application and restrictions would only serve to confuse other developers when things mysteriously don't work. Any idea why it's set that way?... it has no whitelist rules so it's disallowing it. I still don't understand why it would restrict anything like that in a dev-only tool.

In this case, the allowing of navigation of urls wasn't something we considered so we just never put it in. I suppose we could include it in the next release. 

For the CSP modification that's done by `connect-phonegap` - we've tried to modify the user's CSP in such a way that makes it as open as possible. It's a bit janky, I'll admit. However modifying the user's CSP is needed in certain cases where a user's CSP might interfere with the communication needed between `connect-phonegap` and the PhoneGap Developer App.

**Comment by Timkin** [comment]
Hi guys,

As I have nothing to do with this project and I received the initial email in error, could you please discontinue including me in the conversation.

Thanks and regards,

Tim
---

Dr Tim Wilkin
Senior Lecturer | Course Director – Computer Science
School of Information Technology,
Faculty of Science Engineering & Built Environment

[cid:image001.png@01D2E9B5.BB125960]
Deakin University
221 Burwood Highway, Burwood, VIC 3126
+61 3 92517714
tim.wilkin@deakin.edu.au<mailto:tim.wilkin@deakin.edu.au>
www.deakin.edu.au<http://www.deakin.edu.au/>
Deakin University CRICOS Provider Code 00113B

Important Notice: The contents of this email are intended solely for the named addressee and are confidential; any unauthorised use, reproduction or storage of the contents is expressly prohibited. If you have received this email in error, please delete it and any attachments immediately and advise the sender by return email or telephone.

Deakin University does not warrant that this email and any attachments are error or virus free.

**Comment by tisdall** [comment]
@Timkin - sorry!  I didn't realize github names were case sensitive! 

I'm going to close this issue since it's unrelated to this project.
