### ISSUE TITLE
Preserve other console properties on non-browser device

### ISSUE THREAD

**Issue by NgoKimPhu** [phonegap/connect-phonegap#203]
### Issue
Black screen on `Phonegap Developer App` for apps using `React` framework in non-production environment:
```TypeError: console.debug is not a function```
### PhoneGap CLI, node, npm & others' versions
phonegap 6.5.2
node 6.11.0
npm 3.10.10
react 0.14.9
### Expected Behaviour
Apps loaded via `Phonegap Developer App` should work the same way as when connecting directly to the address through browser
### Actual Behaviour
Black screen
### Steps to Reproduce 
`phonegap serve` an app written with React framework and packed with browserify. `react.js` script will crash due to `TypeError: console.debug is not a function`
#### Sample Code that illustrates the problem
`console.debug('Crash me');`
#### Error messages
`TypeError: console.debug is not a function`
#### Suggestions
Apply changes made to [/res/middleware/consoler-http.js](https://github.com/phonegap/connect-phonegap/blob/ec15357/res/middleware/consoler-http.js) in #168 to [/res/middleware/consoler.js](https://github.com/phonegap/connect-phonegap/blob/master/res/middleware/consoler.js)

**Comment by timkim** [comment]
Merged in this commit: https://github.com/phonegap/connect-phonegap/commit/88c8fad8c5403eb1e76b984dc4b75d48fc605108

Thanks again!
