### ISSUE TITLE
Add support for JavaScript-only Plugins

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/connect-phonegap#54]
Reference: [phonegap-cli#315](https://github.com/phonegap/phonegap-cli/issues/315#issuecomment-43264474)

While supporting all third-party plugins is still a ways out, we could add support for JavaScript-only plugins.

Ideally, `connect-phonegap` can use the prepare method to bundle the correct JavaScript elements before serving the files. If we cannot use the cordova prepare method due to SDK dependencies, then we could manually inspect the `plugins/` directory.

**Comment by timkim** [comment]
With the 1.5.2 release, any one can now include their own 3rd party plugin (native and/or javascript only). No modifications needed on the `connect-phonegap` side.

**Comment by RomainFallet** [comment]
So what is the way to do that ? Using only `phonegap serve` on a phonegap project that contains plugins does not work.
