### ISSUE TITLE
Test File Overrides

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/connect-phonegap#55]
Any file in `www/` should be served before looking it up elsewhere.

For example, a `www/cordova.js` would override the `cordova.js` served by connect-phonegap. Likewise, any plugin or `cordova_plugins.js` should support overriding.

I'm hit a few issues where this wasn't happening. I'm creating this issue to test it deeper because I'm unsure if it's legit or just me.

**Comment by filmaj** [comment]
Sorry @mwbrooks I lack the context for this issue. Is it still valid? If so, can you try to explain it to me so I can understand how we can go about tackling it?

**Comment by filmaj** [comment]
@surajpindoria @timkim maybe either of you can comment on what this one's about?

**Comment by surajpindoria** [comment]
Probably good to close this. From what I can tell from Mike's original post this is pre content-sync era of `connect-phonegap`, so no longer relevant.

**Comment by timkim** [comment]
Ya, don't worry about this one - content-sync solved this issue.
