### ISSUE TITLE
Audit and Update Plugin JavaScript Files

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/connect-phonegap#66]
It looks as though some of the plugin JavaScript files bundled in `connect-phonegap` are not the same as those bundled in the `phonegap-app-developer`. It's important the the files are identical because it's plugins often update the JavaScript between versions.

Let's resync (e.g. copy from `phonegap-app-developer`) all of the files found in: [/res/middleware/cordova](https://github.com/phonegap/connect-phonegap/tree/master/res/middleware/cordova)

**Comment by filmaj** [comment]
From what I understand, with content-sync these files are no longer needed. Filed #190 to remove these files in a future release.
