### ISSUE TITLE
Route autoreload through socket

### ISSUE THREAD

**Issue by purplecabbage** [phonegap/connect-phonegap#70]
The console.log socket + socket.io is generic enough that it can also be used to send the autoreload messages, instead of the polling xhr in use now.

**Comment by omefire** [comment]
+1. 
I'm planning on implementing the autoreload through sockets and see if it improves performance.

**Comment by omefire** [comment]
Hmmm, it seems like the 'autoreload' might not be implemented through socket.io because of the pain some Windows users encounter : https://github.com/phonegap/connect-phonegap/issues/79

devs, could you please confirm / infirm ?

**Comment by timkim** [comment]
Hi @omefire 

Ya, that's part of the reason. The other part is that we wanted a very simple polling interface that had no dependencies.

**Comment by filmaj** [comment]
It's been a while, but do we still want to consider reimplementing how autoreload works, as described in here? @purplecabbage @timkim ?

**Comment by purplecabbage** [comment]
the windows issue is a non-issue with current socket.io
I don't think this is a priority though, really it was just to prevent interval pinging of the server.
