### ISSUE TITLE
Change default IP address in a multi NIC setup

### ISSUE THREAD

**Issue by nethatix** [phonegap/connect-phonegap#77]
Hi,

I have multiple NIC adapters on my computers. When invoking phonegap serve it launches on my corporate IP address 192.168.224.xx That lan is not accessible to my devices and the app fails to connect.

I have a wireless NIC(s) with IP on 192.168.1.4 which is accessible to my mob devices.

How do I go about changing the IP?
Thanks

**Comment by itree** [comment]
Hi is this option added?   Currently I'm using the latest phonegap  and when I run phonegap serve

I get this wired IP:
[phonegap] listening on 127.0.0.53:3000

Which is totally useless as it can only be accessed on the local computer and not from a mobile device on the same network. 
~$ phonegap version
5.0.0-0.28.1

**Comment by mwbrooks** [comment]
Hey all, I've just published support for displaying all available network addresses that are IPv4 and not internal. The first address listed the the PG CLI's best guess at the public network interface.

On most systems, there is only one network address. However, when more are available they will be listed. Hope this helps!
