### ISSUE TITLE
Console logging [#57] adds dependency on socket.io that fails to build on many Windows hosts

### ISSUE THREAD

**Issue by tohagan** [phonegap/connect-phonegap#79]
Adding socket.io requires the user to have Visual Studio 2010 installed which will significantly reduce the number of developers who can install this tool.

I get this error.  Attempting to upgrade to another version of Visual Studio also fails as later version don't appear to support the VS project type.  I happen to have VS 2012 and 2013 installed but neither can compile socket.io .

A fix may be to roll back to an earlier version of socket.io but this may also complicate your future version support.

d:\Projects\STLIVE\connect-phonegap\node_modules\socket.io\node_modules\engine.io\node_modules\ws>node "c:\Program Files
 (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please in
stall Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [d:\Projects\STLIVE\connect-phon
egap\node_modules\socket.io\node_modules\engine.io\node_modules\ws\build\bufferutil.vcxproj]

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please in
stall Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [d:\Projects\STLIVE\connect-phon
egap\node_modules\socket.io\node_modules\engine.io\node_modules\ws\build\validation.vcxproj]

**Comment by purplecabbage** [comment]
akaik this is no longer an issue, addressed elsewhere.
Please retest and reopen if you feel I am wrong.
