### ISSUE TITLE
Fix filename case for inappbrowser plugin

### ISSUE THREAD

**Issue by baverman** [phonegap/connect-phonegap#95]
res/middleware/cordova/3.5.0/ios/plugins/org.apache.cordova.inappbrowser/www/InAppBrowser.js

Current name leads to error:
<pre>
Error: ENOENT, no such file or directory '/usr/lib/node_modules/phonegap/node_modules/connect-phonegap/res/middleware/cordova/3.5.0/ios/plugins/org.apache.cordova.inappbrowser/www/inappbrowser.js'
</pre>

**Comment by mwbrooks** [comment]
A little slow, but this has been resolved. Thanks for submitting the issue @baverman!
